package com.jefferson.cursojava.aula20;

public class MatrizesParte4 {
    public static void main(String[] args) {


    }
}

/*
 * Ex: Matrizes Irregulares
 *
 * ESCREVA UM PROGRAMA PARA GUARDAR DADOS DE UMA PESQUISA FEITA COM UMA AMOSTRA DE PESSOAS DA AVENIDA MAIS MOVIMENTADA DA CIDADE ONDE VOCE MORA.
 * A PESQUISA CONSISTE EM PERGUNTAR AO CIDADAO A QUANTIDADE DE FILHOS E O NOME DE CADA FILHO. GUARDE ESSAS INFORMAÇÕES EM UMA MATRIZ DE FORMA QUE CADA PESSOA
 * ENTREVISTADA OCUPE SOMENTE O ESPAÇO NECESSARIO NA MEMORIA PARA GUARDAR OS NOMES DOS FILHOS.
 * IMPRIMA A QUANTIDADE DE PESSOAS ENTREVISTADAS, A QUANTIDADE DE FILHOS DE CADA ENTREVISTADO E OS RESPECTIVOS NOMES DOS FILHOS.
 */